USE [Curso]

ALTER TABLE [Aluno]
    ADD [Document] NVARCHAR(11)

ALTER TABLE [Aluno]
    DROP COLUMN [Document]

ALTER TABLE [Aluno]
    ADD [Document] CHAR(11)


DROP TABLE Aluno

CREATE TABLE [Aluno](
    [Id] INT NOT NULL,
    [Nome] NVARCHAR(80) NOT NULL,
    [Email] NVARCHAR(180) NOT NULL UNIQUE,
    [Nascimento] DATETIME NULL,
    [Active] BIT DEFAULT(0) 
)

DROP TABLE Aluno

CREATE TABLE [Aluno](
    [Id] INT NOT NULL,
    [Nome] NVARCHAR(80) NOT NULL,
    [Email] NVARCHAR(180) NOT NULL UNIQUE,
    [Nascimento] DATETIME NULL,
    [Active] BIT DEFAULT(0)

    PRIMARY KEY([Id])
)

--HE POSSIVEL NOMERAR AS CHAVES, BASTA COLOAR A CONSTRANT NA FRENTE
DROP TABLE Aluno

CREATE TABLE [Aluno](
    [Id] INT NOT NULL,
    [Nome] NVARCHAR(80) NOT NULL,
    [Email] NVARCHAR(180) NOT NULL,
    [Nascimento] DATETIME NULL,
    [Active] BIT DEFAULT(0)

    CONSTRAINT [PK_ALUNO_ID] PRIMARY KEY([Id]),
    CONSTRAINT [UQ_ALUNO_EMAIL] UNIQUE([Email])
)

ALTER TABLE [Aluno]
    DROP CONSTRAINT[UQ_Aluno_A9D10534083EA5B8]