USE [Curso]

ALTER TABLE [Aluno]
    ADD [Document] NVARCHAR(11)

ALTER TABLE [Aluno]
    DROP COLUMN [Document]

ALTER TABLE [Aluno]
    ADD [Document] CHAR(11)


DROP TABLE Aluno

CREATE TABLE [Aluno](
    [Id] INT NOT NULL,
    [Nome] NVARCHAR(80) NOT NULL,
    [Email] NVARCHAR(180) NOT NULL UNIQUE,
    [Nascimento] DATETIME NULL,
    [Active] BIT DEFAULT(0) 
)

DROP TABLE Aluno

CREATE TABLE [Aluno](
    [Id] INT NOT NULL,
    [Nome] NVARCHAR(80) NOT NULL,
    [Email] NVARCHAR(180) NOT NULL UNIQUE,
    [Nascimento] DATETIME NULL,
    [Active] BIT DEFAULT(0)

    PRIMARY KEY([Id])
)

--HE POSSIVEL NOMERAR AS CHAVES, BASTA COLOAR A CONSTRANT NA FRENTE
DROP TABLE Aluno

CREATE TABLE [Aluno](
    [Id] INT NOT NULL,
    [Nome] NVARCHAR(80) NOT NULL,
    [Email] NVARCHAR(180) NOT NULL,
    [Nascimento] DATETIME NULL,
    [Active] BIT DEFAULT(0)

    CONSTRAINT [PK_ALUNO_ID] PRIMARY KEY([Id]),
    CONSTRAINT [UQ_ALUNO_EMAIL] UNIQUE([Email])
)


CREATE TABLE [Curso](
    [Id] INT NOT NULL,
    [Nome] NVARCHAR(80) NOT NULL,
    [CategoriaId] INT NOT NULL

    CONSTRAINT [PK_CURSO_ID] PRIMARY KEY([Id]),    
    CONSTRAINT [FK_CURSO_CATEGORIA] FOREIGN KEY([CategoriaId])    
        REFERENCES [Categoria]([Id])
)

CREATE TABLE [ProgressoCurso](
    [AlunoId] INT NOT NULL,
    [CursoId] INT NOT NULL,
    [Progresso] INT NOT NULL,
    [UltimaAtualizacao] DATETIME DEFAULT(GETDATE())

    CONSTRAINT PK_PROGRESSO_CURSO PRIMARY KEY([AlunoId], [CursoId])

)

CREATE TABLE [Categoria](
    [Id] INT NOT NULL,
    [Nome] NVARCHAR(80) NOT NULL,

    CONSTRAINT [PK_CATEGORIA_ID] PRIMARY KEY([Id])    
)